// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/admin/v1/rpc.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/gonotelm-lab/flow/api/schema/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *v1.Namespace          `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNamespaceRequest) Reset() {
	*x = CreateNamespaceRequest{}
	mi := &file_api_admin_v1_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceRequest) ProtoMessage() {}

func (x *CreateNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceRequest.ProtoReflect.Descriptor instead.
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNamespaceRequest) GetNamespace() *v1.Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

type GetNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceRequest) Reset() {
	*x = GetNamespaceRequest{}
	mi := &file_api_admin_v1_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceRequest) ProtoMessage() {}

func (x *GetNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceRequest.ProtoReflect.Descriptor instead.
func (*GetNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_admin_v1_rpc_proto protoreflect.FileDescriptor

const file_api_admin_v1_rpc_proto_rawDesc = "" +
	"\n" +
	"\x16api/admin/v1/rpc.proto\x12\fapi.admin.v1\x1a\x1dapi/schema/v1/namespace.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"U\n" +
	"\x16CreateNamespaceRequest\x12;\n" +
	"\tnamespace\x18\x01 \x01(\v2\x18.api.schema.v1.NamespaceB\x03\xe0A\x02R\tnamespace\"4\n" +
	"\x13GetNamespaceRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\x04name2\x84\x02\n" +
	"\fAdminService\x12~\n" +
	"\x0fCreateNamespace\x12$.api.admin.v1.CreateNamespaceRequest\x1a\x18.api.schema.v1.Namespace\"+\x82\xd3\xe4\x93\x02%:\tnamespace\"\x18/api/admin/v1/namespaces\x12t\n" +
	"\fGetNamespace\x12!.api.admin.v1.GetNamespaceRequest\x1a\x18.api.schema.v1.Namespace\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/admin/v1/namespaces/{name}B\x99\x01\n" +
	"\x10com.api.admin.v1B\bRpcProtoP\x01Z)github.com/gonotelm-lab/flow/api/admin/v1\xa2\x02\x03AAX\xaa\x02\fApi.Admin.V1\xca\x02\fApi\\Admin\\V1\xe2\x02\x18Api\\Admin\\V1\\GPBMetadata\xea\x02\x0eApi::Admin::V1b\x06proto3"

var (
	file_api_admin_v1_rpc_proto_rawDescOnce sync.Once
	file_api_admin_v1_rpc_proto_rawDescData []byte
)

func file_api_admin_v1_rpc_proto_rawDescGZIP() []byte {
	file_api_admin_v1_rpc_proto_rawDescOnce.Do(func() {
		file_api_admin_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_admin_v1_rpc_proto_rawDesc), len(file_api_admin_v1_rpc_proto_rawDesc)))
	})
	return file_api_admin_v1_rpc_proto_rawDescData
}

var file_api_admin_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_admin_v1_rpc_proto_goTypes = []any{
	(*CreateNamespaceRequest)(nil), // 0: api.admin.v1.CreateNamespaceRequest
	(*GetNamespaceRequest)(nil),    // 1: api.admin.v1.GetNamespaceRequest
	(*v1.Namespace)(nil),           // 2: api.schema.v1.Namespace
}
var file_api_admin_v1_rpc_proto_depIdxs = []int32{
	2, // 0: api.admin.v1.CreateNamespaceRequest.namespace:type_name -> api.schema.v1.Namespace
	0, // 1: api.admin.v1.AdminService.CreateNamespace:input_type -> api.admin.v1.CreateNamespaceRequest
	1, // 2: api.admin.v1.AdminService.GetNamespace:input_type -> api.admin.v1.GetNamespaceRequest
	2, // 3: api.admin.v1.AdminService.CreateNamespace:output_type -> api.schema.v1.Namespace
	2, // 4: api.admin.v1.AdminService.GetNamespace:output_type -> api.schema.v1.Namespace
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_admin_v1_rpc_proto_init() }
func file_api_admin_v1_rpc_proto_init() {
	if File_api_admin_v1_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_admin_v1_rpc_proto_rawDesc), len(file_api_admin_v1_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_admin_v1_rpc_proto_goTypes,
		DependencyIndexes: file_api_admin_v1_rpc_proto_depIdxs,
		MessageInfos:      file_api_admin_v1_rpc_proto_msgTypes,
	}.Build()
	File_api_admin_v1_rpc_proto = out.File
	file_api_admin_v1_rpc_proto_goTypes = nil
	file_api_admin_v1_rpc_proto_depIdxs = nil
}
