// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/schema/v1/namespace.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Namespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Creator       string                 `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	ApiKey        string                 `protobuf:"bytes,6,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiKeyPreview string                 `protobuf:"bytes,7,opt,name=api_key_preview,json=apiKeyPreview,proto3" json:"api_key_preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_api_schema_v1_namespace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_api_schema_v1_namespace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_api_schema_v1_namespace_proto_rawDescGZIP(), []int{0}
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Namespace) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Namespace) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Namespace) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Namespace) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Namespace) GetApiKeyPreview() string {
	if x != nil {
		return x.ApiKeyPreview
	}
	return ""
}

var File_api_schema_v1_namespace_proto protoreflect.FileDescriptor

const file_api_schema_v1_namespace_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/schema/v1/namespace.proto\x12\rapi.schema.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x02\n" +
	"\tNamespace\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\acreator\x18\x03 \x01(\tR\acreator\x12@\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12\x1c\n" +
	"\aapi_key\x18\x06 \x01(\tB\x03\xe0A\x03R\x06apiKey\x12+\n" +
	"\x0fapi_key_preview\x18\a \x01(\tB\x03\xe0A\x03R\rapiKeyPreviewB\xa5\x01\n" +
	"\x11com.api.schema.v1B\x0eNamespaceProtoP\x01Z*github.com/gonotelm-lab/flow/api/schema/v1\xa2\x02\x03ASX\xaa\x02\rApi.Schema.V1\xca\x02\rApi\\Schema\\V1\xe2\x02\x19Api\\Schema\\V1\\GPBMetadata\xea\x02\x0fApi::Schema::V1b\x06proto3"

var (
	file_api_schema_v1_namespace_proto_rawDescOnce sync.Once
	file_api_schema_v1_namespace_proto_rawDescData []byte
)

func file_api_schema_v1_namespace_proto_rawDescGZIP() []byte {
	file_api_schema_v1_namespace_proto_rawDescOnce.Do(func() {
		file_api_schema_v1_namespace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_schema_v1_namespace_proto_rawDesc), len(file_api_schema_v1_namespace_proto_rawDesc)))
	})
	return file_api_schema_v1_namespace_proto_rawDescData
}

var file_api_schema_v1_namespace_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_schema_v1_namespace_proto_goTypes = []any{
	(*Namespace)(nil),             // 0: api.schema.v1.Namespace
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_api_schema_v1_namespace_proto_depIdxs = []int32{
	1, // 0: api.schema.v1.Namespace.create_time:type_name -> google.protobuf.Timestamp
	1, // 1: api.schema.v1.Namespace.update_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_schema_v1_namespace_proto_init() }
func file_api_schema_v1_namespace_proto_init() {
	if File_api_schema_v1_namespace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_schema_v1_namespace_proto_rawDesc), len(file_api_schema_v1_namespace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_schema_v1_namespace_proto_goTypes,
		DependencyIndexes: file_api_schema_v1_namespace_proto_depIdxs,
		MessageInfos:      file_api_schema_v1_namespace_proto_msgTypes,
	}.Build()
	File_api_schema_v1_namespace_proto = out.File
	file_api_schema_v1_namespace_proto_goTypes = nil
	file_api_schema_v1_namespace_proto_depIdxs = nil
}
