// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/schema/v1/task.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_INITED                 TaskState = 1
	TaskState_RUNNING                TaskState = 2
	TaskState_DONE                   TaskState = 3
	TaskState_FAILED                 TaskState = 4
	TaskState_CANCELLED              TaskState = 5
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "INITED",
		2: "RUNNING",
		3: "DONE",
		4: "FAILED",
		5: "CANCELLED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"INITED":                 1,
		"RUNNING":                2,
		"DONE":                   3,
		"FAILED":                 4,
		"CANCELLED":              5,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_schema_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_api_schema_v1_task_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_api_schema_v1_task_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TaskType      string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Result        []byte                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Error         []byte                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	State         TaskState              `protobuf:"varint,7,opt,name=state,proto3,enum=api.schema.v1.TaskState" json:"state,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	NextRunTime   int64                  `protobuf:"varint,10,opt,name=next_run_time,json=nextRunTime,proto3" json:"next_run_time,omitempty"`
	MaxRetry      int64                  `protobuf:"varint,11,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`
	AttemptNo     int32                  `protobuf:"varint,12,opt,name=attempt_no,json=attemptNo,proto3" json:"attempt_no,omitempty"`
	WorkerId      int64                  `protobuf:"varint,13,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_schema_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_schema_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_schema_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Task) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *Task) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Task) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Task) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *Task) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Task) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Task) GetNextRunTime() int64 {
	if x != nil {
		return x.NextRunTime
	}
	return 0
}

func (x *Task) GetMaxRetry() int64 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *Task) GetAttemptNo() int32 {
	if x != nil {
		return x.AttemptNo
	}
	return 0
}

func (x *Task) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

var File_api_schema_v1_task_proto protoreflect.FileDescriptor

const file_api_schema_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x18api/schema/v1/task.proto\x12\rapi.schema.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x04\n" +
	"\x04Task\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xe0A\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12(\n" +
	"\tnamespace\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\tnamespace\x12'\n" +
	"\ttask_type\x18\x03 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\btaskType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1b\n" +
	"\x06result\x18\x05 \x01(\fB\x03\xe0A\x03R\x06result\x12\x19\n" +
	"\x05error\x18\x06 \x01(\fB\x03\xe0A\x03R\x05error\x12;\n" +
	"\x05state\x18\a \x01(\x0e2\x18.api.schema.v1.TaskStateB\v\xe0A\x03\xbaH\x05\x82\x01\x02\x10\x01R\x05state\x12@\n" +
	"\vcreate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12'\n" +
	"\rnext_run_time\x18\n" +
	" \x01(\x03B\x03\xe0A\x03R\vnextRunTime\x12$\n" +
	"\tmax_retry\x18\v \x01(\x03B\a\xbaH\x04\"\x02(\x00R\bmaxRetry\x12\"\n" +
	"\n" +
	"attempt_no\x18\f \x01(\x05B\x03\xe0A\x03R\tattemptNo\x12 \n" +
	"\tworker_id\x18\r \x01(\x03B\x03\xe0A\x03R\bworkerId*e\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06INITED\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\b\n" +
	"\x04DONE\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x05B\xa0\x01\n" +
	"\x11com.api.schema.v1B\tTaskProtoP\x01Z*github.com/gonotelm-lab/flow/api/schema/v1\xa2\x02\x03ASX\xaa\x02\rApi.Schema.V1\xca\x02\rApi\\Schema\\V1\xe2\x02\x19Api\\Schema\\V1\\GPBMetadata\xea\x02\x0fApi::Schema::V1b\x06proto3"

var (
	file_api_schema_v1_task_proto_rawDescOnce sync.Once
	file_api_schema_v1_task_proto_rawDescData []byte
)

func file_api_schema_v1_task_proto_rawDescGZIP() []byte {
	file_api_schema_v1_task_proto_rawDescOnce.Do(func() {
		file_api_schema_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_schema_v1_task_proto_rawDesc), len(file_api_schema_v1_task_proto_rawDesc)))
	})
	return file_api_schema_v1_task_proto_rawDescData
}

var file_api_schema_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_schema_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_schema_v1_task_proto_goTypes = []any{
	(TaskState)(0),                // 0: api.schema.v1.TaskState
	(*Task)(nil),                  // 1: api.schema.v1.Task
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_schema_v1_task_proto_depIdxs = []int32{
	0, // 0: api.schema.v1.Task.state:type_name -> api.schema.v1.TaskState
	2, // 1: api.schema.v1.Task.create_time:type_name -> google.protobuf.Timestamp
	2, // 2: api.schema.v1.Task.update_time:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_schema_v1_task_proto_init() }
func file_api_schema_v1_task_proto_init() {
	if File_api_schema_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_schema_v1_task_proto_rawDesc), len(file_api_schema_v1_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_schema_v1_task_proto_goTypes,
		DependencyIndexes: file_api_schema_v1_task_proto_depIdxs,
		EnumInfos:         file_api_schema_v1_task_proto_enumTypes,
		MessageInfos:      file_api_schema_v1_task_proto_msgTypes,
	}.Build()
	File_api_schema_v1_task_proto = out.File
	file_api_schema_v1_task_proto_goTypes = nil
	file_api_schema_v1_task_proto_depIdxs = nil
}
