// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/schema/v1/taskevent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	CreateTime    int64                  `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_api_schema_v1_taskevent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_schema_v1_taskevent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_api_schema_v1_taskevent_proto_rawDescGZIP(), []int{0}
}

func (x *TaskEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TaskEvent) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *TaskEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_api_schema_v1_taskevent_proto protoreflect.FileDescriptor

const file_api_schema_v1_taskevent_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/schema/v1/taskevent.proto\x12\rapi.schema.v1\"\x8e\x01\n" +
	"\tTaskEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\x03R\n" +
	"createTime\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayloadB\xa5\x01\n" +
	"\x11com.api.schema.v1B\x0eTaskeventProtoP\x01Z*github.com/gonotelm-lab/flow/api/schema/v1\xa2\x02\x03ASX\xaa\x02\rApi.Schema.V1\xca\x02\rApi\\Schema\\V1\xe2\x02\x19Api\\Schema\\V1\\GPBMetadata\xea\x02\x0fApi::Schema::V1b\x06proto3"

var (
	file_api_schema_v1_taskevent_proto_rawDescOnce sync.Once
	file_api_schema_v1_taskevent_proto_rawDescData []byte
)

func file_api_schema_v1_taskevent_proto_rawDescGZIP() []byte {
	file_api_schema_v1_taskevent_proto_rawDescOnce.Do(func() {
		file_api_schema_v1_taskevent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_schema_v1_taskevent_proto_rawDesc), len(file_api_schema_v1_taskevent_proto_rawDesc)))
	})
	return file_api_schema_v1_taskevent_proto_rawDescData
}

var file_api_schema_v1_taskevent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_schema_v1_taskevent_proto_goTypes = []any{
	(*TaskEvent)(nil), // 0: api.schema.v1.TaskEvent
}
var file_api_schema_v1_taskevent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_schema_v1_taskevent_proto_init() }
func file_api_schema_v1_taskevent_proto_init() {
	if File_api_schema_v1_taskevent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_schema_v1_taskevent_proto_rawDesc), len(file_api_schema_v1_taskevent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_schema_v1_taskevent_proto_goTypes,
		DependencyIndexes: file_api_schema_v1_taskevent_proto_depIdxs,
		MessageInfos:      file_api_schema_v1_taskevent_proto_msgTypes,
	}.Build()
	File_api_schema_v1_taskevent_proto = out.File
	file_api_schema_v1_taskevent_proto_goTypes = nil
	file_api_schema_v1_taskevent_proto_depIdxs = nil
}
