// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/schema/v1/worker.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Worker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TaskType      string                 `protobuf:"bytes,4,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	HeartbeatTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=heartbeat_time,json=heartbeatTime,proto3" json:"heartbeat_time,omitempty"`
	LastWorkTime  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_work_time,json=lastWorkTime,proto3" json:"last_work_time,omitempty"`
	TotalDealt    int64                  `protobuf:"varint,8,opt,name=total_dealt,json=totalDealt,proto3" json:"total_dealt,omitempty"`
	SuccessDealt  int64                  `protobuf:"varint,9,opt,name=success_dealt,json=successDealt,proto3" json:"success_dealt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_api_schema_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_api_schema_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_api_schema_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *Worker) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Worker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Worker) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Worker) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *Worker) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Worker) GetHeartbeatTime() *timestamppb.Timestamp {
	if x != nil {
		return x.HeartbeatTime
	}
	return nil
}

func (x *Worker) GetLastWorkTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastWorkTime
	}
	return nil
}

func (x *Worker) GetTotalDealt() int64 {
	if x != nil {
		return x.TotalDealt
	}
	return 0
}

func (x *Worker) GetSuccessDealt() int64 {
	if x != nil {
		return x.SuccessDealt
	}
	return 0
}

var File_api_schema_v1_worker_proto protoreflect.FileDescriptor

const file_api_schema_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/schema/v1/worker.proto\x12\rapi.schema.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x03\n" +
	"\x06Worker\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\x03B\r\xe0A\b\xe0A\x03\xbaH\x04\"\x02 \x00R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\tnamespace\x18\x03 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\tnamespace\x12'\n" +
	"\ttask_type\x18\x04 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\btaskType\x12@\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12F\n" +
	"\x0eheartbeat_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\rheartbeatTime\x12E\n" +
	"\x0elast_work_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\flastWorkTime\x12$\n" +
	"\vtotal_dealt\x18\b \x01(\x03B\x03\xe0A\x03R\n" +
	"totalDealt\x12(\n" +
	"\rsuccess_dealt\x18\t \x01(\x03B\x03\xe0A\x03R\fsuccessDealtB\xa2\x01\n" +
	"\x11com.api.schema.v1B\vWorkerProtoP\x01Z*github.com/gonotelm-lab/flow/api/schema/v1\xa2\x02\x03ASX\xaa\x02\rApi.Schema.V1\xca\x02\rApi\\Schema\\V1\xe2\x02\x19Api\\Schema\\V1\\GPBMetadata\xea\x02\x0fApi::Schema::V1b\x06proto3"

var (
	file_api_schema_v1_worker_proto_rawDescOnce sync.Once
	file_api_schema_v1_worker_proto_rawDescData []byte
)

func file_api_schema_v1_worker_proto_rawDescGZIP() []byte {
	file_api_schema_v1_worker_proto_rawDescOnce.Do(func() {
		file_api_schema_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_schema_v1_worker_proto_rawDesc), len(file_api_schema_v1_worker_proto_rawDesc)))
	})
	return file_api_schema_v1_worker_proto_rawDescData
}

var file_api_schema_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_schema_v1_worker_proto_goTypes = []any{
	(*Worker)(nil),                // 0: api.schema.v1.Worker
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_api_schema_v1_worker_proto_depIdxs = []int32{
	1, // 0: api.schema.v1.Worker.create_time:type_name -> google.protobuf.Timestamp
	1, // 1: api.schema.v1.Worker.heartbeat_time:type_name -> google.protobuf.Timestamp
	1, // 2: api.schema.v1.Worker.last_work_time:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_schema_v1_worker_proto_init() }
func file_api_schema_v1_worker_proto_init() {
	if File_api_schema_v1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_schema_v1_worker_proto_rawDesc), len(file_api_schema_v1_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_schema_v1_worker_proto_goTypes,
		DependencyIndexes: file_api_schema_v1_worker_proto_depIdxs,
		MessageInfos:      file_api_schema_v1_worker_proto_msgTypes,
	}.Build()
	File_api_schema_v1_worker_proto = out.File
	file_api_schema_v1_worker_proto_goTypes = nil
	file_api_schema_v1_worker_proto_depIdxs = nil
}
