// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/task/v1/rpc.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/gonotelm-lab/flow/api/schema/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TaskType      string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	MaxRetry      int64                  `protobuf:"varint,4,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_api_task_v1_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_api_task_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SubmitRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *SubmitRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubmitRequest) GetMaxRetry() int64 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *v1.Task               `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_api_task_v1_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_api_task_v1_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResponse) GetTask() *v1.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_task_v1_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_task_v1_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *v1.Task               `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_task_v1_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_task_v1_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetTask() *v1.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_api_task_v1_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_api_task_v1_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_api_task_v1_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_v1_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_api_task_v1_rpc_proto_rawDescGZIP(), []int{5}
}

var File_api_task_v1_rpc_proto protoreflect.FileDescriptor

const file_api_task_v1_rpc_proto_rawDesc = "" +
	"\n" +
	"\x15api/task/v1/rpc.proto\x12\vapi.task.v1\x1a\x18api/schema/v1/task.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xa2\x01\n" +
	"\rSubmitRequest\x12(\n" +
	"\tnamespace\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\tnamespace\x12'\n" +
	"\ttask_type\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\btaskType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12$\n" +
	"\tmax_retry\x18\x04 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\bmaxRetry\">\n" +
	"\x0eSubmitResponse\x12,\n" +
	"\x04task\x18\x01 \x01(\v2\x13.api.schema.v1.TaskB\x03\xe0A\x03R\x04task\")\n" +
	"\n" +
	"GetRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\";\n" +
	"\vGetResponse\x12,\n" +
	"\x04task\x18\x01 \x01(\v2\x13.api.schema.v1.TaskB\x03\xe0A\x03R\x04task\",\n" +
	"\rCancelRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\"\x10\n" +
	"\x0eCancelResponse2\xcd\x01\n" +
	"\vTaskService\x12A\n" +
	"\x06Submit\x12\x1a.api.task.v1.SubmitRequest\x1a\x1b.api.task.v1.SubmitResponse\x128\n" +
	"\x03Get\x12\x17.api.task.v1.GetRequest\x1a\x18.api.task.v1.GetResponse\x12A\n" +
	"\x06Cancel\x12\x1a.api.task.v1.CancelRequest\x1a\x1b.api.task.v1.CancelResponseB\x93\x01\n" +
	"\x0fcom.api.task.v1B\bRpcProtoP\x01Z(github.com/gonotelm-lab/flow/api/task/v1\xa2\x02\x03ATX\xaa\x02\vApi.Task.V1\xca\x02\vApi\\Task\\V1\xe2\x02\x17Api\\Task\\V1\\GPBMetadata\xea\x02\rApi::Task::V1b\x06proto3"

var (
	file_api_task_v1_rpc_proto_rawDescOnce sync.Once
	file_api_task_v1_rpc_proto_rawDescData []byte
)

func file_api_task_v1_rpc_proto_rawDescGZIP() []byte {
	file_api_task_v1_rpc_proto_rawDescOnce.Do(func() {
		file_api_task_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_task_v1_rpc_proto_rawDesc), len(file_api_task_v1_rpc_proto_rawDesc)))
	})
	return file_api_task_v1_rpc_proto_rawDescData
}

var file_api_task_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_task_v1_rpc_proto_goTypes = []any{
	(*SubmitRequest)(nil),  // 0: api.task.v1.SubmitRequest
	(*SubmitResponse)(nil), // 1: api.task.v1.SubmitResponse
	(*GetRequest)(nil),     // 2: api.task.v1.GetRequest
	(*GetResponse)(nil),    // 3: api.task.v1.GetResponse
	(*CancelRequest)(nil),  // 4: api.task.v1.CancelRequest
	(*CancelResponse)(nil), // 5: api.task.v1.CancelResponse
	(*v1.Task)(nil),        // 6: api.schema.v1.Task
}
var file_api_task_v1_rpc_proto_depIdxs = []int32{
	6, // 0: api.task.v1.SubmitResponse.task:type_name -> api.schema.v1.Task
	6, // 1: api.task.v1.GetResponse.task:type_name -> api.schema.v1.Task
	0, // 2: api.task.v1.TaskService.Submit:input_type -> api.task.v1.SubmitRequest
	2, // 3: api.task.v1.TaskService.Get:input_type -> api.task.v1.GetRequest
	4, // 4: api.task.v1.TaskService.Cancel:input_type -> api.task.v1.CancelRequest
	1, // 5: api.task.v1.TaskService.Submit:output_type -> api.task.v1.SubmitResponse
	3, // 6: api.task.v1.TaskService.Get:output_type -> api.task.v1.GetResponse
	5, // 7: api.task.v1.TaskService.Cancel:output_type -> api.task.v1.CancelResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_task_v1_rpc_proto_init() }
func file_api_task_v1_rpc_proto_init() {
	if File_api_task_v1_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_task_v1_rpc_proto_rawDesc), len(file_api_task_v1_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_task_v1_rpc_proto_goTypes,
		DependencyIndexes: file_api_task_v1_rpc_proto_depIdxs,
		MessageInfos:      file_api_task_v1_rpc_proto_msgTypes,
	}.Build()
	File_api_task_v1_rpc_proto = out.File
	file_api_task_v1_rpc_proto_goTypes = nil
	file_api_task_v1_rpc_proto_depIdxs = nil
}
