// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/worker/v1/rpc.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/gonotelm-lab/flow/api/schema/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportAction int32

const (
	ReportAction_REPORT_ACTION_UNSPECIFIED ReportAction = 0
	ReportAction_SUCCESS                   ReportAction = 1
	ReportAction_FAIL                      ReportAction = 2
)

// Enum value maps for ReportAction.
var (
	ReportAction_name = map[int32]string{
		0: "REPORT_ACTION_UNSPECIFIED",
		1: "SUCCESS",
		2: "FAIL",
	}
	ReportAction_value = map[string]int32{
		"REPORT_ACTION_UNSPECIFIED": 0,
		"SUCCESS":                   1,
		"FAIL":                      2,
	}
)

func (x ReportAction) Enum() *ReportAction {
	p := new(ReportAction)
	*p = x
	return p
}

func (x ReportAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_worker_v1_rpc_proto_enumTypes[0].Descriptor()
}

func (ReportAction) Type() protoreflect.EnumType {
	return &file_api_worker_v1_rpc_proto_enumTypes[0]
}

func (x ReportAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportAction.Descriptor instead.
func (ReportAction) EnumDescriptor() ([]byte, []int) {
	return file_api_worker_v1_rpc_proto_rawDescGZIP(), []int{0}
}

type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_api_worker_v1_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_worker_v1_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_api_worker_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *UnregisterRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_api_worker_v1_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_worker_v1_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_api_worker_v1_rpc_proto_rawDescGZIP(), []int{1}
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_worker_v1_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_worker_v1_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_worker_v1_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=heartbeat_time,json=heartbeatTime,proto3" json:"heartbeat_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_worker_v1_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_worker_v1_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_worker_v1_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetHeartbeatTime() *timestamppb.Timestamp {
	if x != nil {
		return x.HeartbeatTime
	}
	return nil
}

type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TaskType      string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_api_worker_v1_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_worker_v1_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_api_worker_v1_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *PollRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PollRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PollRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *v1.Task               `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_api_worker_v1_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_worker_v1_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_api_worker_v1_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *PollResponse) GetTask() *v1.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      int64                  `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Action        ReportAction           `protobuf:"varint,3,opt,name=action,proto3,enum=api.worker.v1.ReportAction" json:"action,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_api_worker_v1_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_worker_v1_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_api_worker_v1_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *ReportRequest) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *ReportRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportRequest) GetAction() ReportAction {
	if x != nil {
		return x.Action
	}
	return ReportAction_REPORT_ACTION_UNSPECIFIED
}

func (x *ReportRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_api_worker_v1_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_worker_v1_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_api_worker_v1_rpc_proto_rawDescGZIP(), []int{7}
}

var File_api_worker_v1_rpc_proto protoreflect.FileDescriptor

const file_api_worker_v1_rpc_proto_rawDesc = "" +
	"\n" +
	"\x17api/worker/v1/rpc.proto\x12\rapi.worker.v1\x1a\x18api/schema/v1/task.proto\x1a\x1aapi/schema/v1/worker.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"+\n" +
	"\x11UnregisterRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\x02id\"\x14\n" +
	"\x12UnregisterResponse\"*\n" +
	"\x10HeartbeatRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\x02id\"[\n" +
	"\x11HeartbeatResponse\x12F\n" +
	"\x0eheartbeat_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\rheartbeatTime\"p\n" +
	"\vPollRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\x02id\x12$\n" +
	"\tnamespace\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tnamespace\x12#\n" +
	"\ttask_type\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\btaskType\"7\n" +
	"\fPollResponse\x12'\n" +
	"\x04task\x18\x01 \x01(\v2\x13.api.schema.v1.TaskR\x04task\"\xb1\x01\n" +
	"\rReportRequest\x12#\n" +
	"\tworker_id\x18\x01 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\bworkerId\x12\x1f\n" +
	"\atask_id\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06taskId\x12@\n" +
	"\x06action\x18\x03 \x01(\x0e2\x1b.api.worker.v1.ReportActionB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\x06action\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\x10\n" +
	"\x0eReportResponse*D\n" +
	"\fReportAction\x12\x1d\n" +
	"\x19REPORT_ACTION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\b\n" +
	"\x04FAIL\x10\x022\xf4\x02\n" +
	"\rWorkerService\x128\n" +
	"\bRegister\x12\x15.api.schema.v1.Worker\x1a\x15.api.schema.v1.Worker\x12Q\n" +
	"\n" +
	"Unregister\x12 .api.worker.v1.UnregisterRequest\x1a!.api.worker.v1.UnregisterResponse\x12N\n" +
	"\tHeartbeat\x12\x1f.api.worker.v1.HeartbeatRequest\x1a .api.worker.v1.HeartbeatResponse\x12?\n" +
	"\x04Poll\x12\x1a.api.worker.v1.PollRequest\x1a\x1b.api.worker.v1.PollResponse\x12E\n" +
	"\x06Report\x12\x1c.api.worker.v1.ReportRequest\x1a\x1d.api.worker.v1.ReportResponseB\x9f\x01\n" +
	"\x11com.api.worker.v1B\bRpcProtoP\x01Z*github.com/gonotelm-lab/flow/api/worker/v1\xa2\x02\x03AWX\xaa\x02\rApi.Worker.V1\xca\x02\rApi\\Worker\\V1\xe2\x02\x19Api\\Worker\\V1\\GPBMetadata\xea\x02\x0fApi::Worker::V1b\x06proto3"

var (
	file_api_worker_v1_rpc_proto_rawDescOnce sync.Once
	file_api_worker_v1_rpc_proto_rawDescData []byte
)

func file_api_worker_v1_rpc_proto_rawDescGZIP() []byte {
	file_api_worker_v1_rpc_proto_rawDescOnce.Do(func() {
		file_api_worker_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_worker_v1_rpc_proto_rawDesc), len(file_api_worker_v1_rpc_proto_rawDesc)))
	})
	return file_api_worker_v1_rpc_proto_rawDescData
}

var file_api_worker_v1_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_worker_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_worker_v1_rpc_proto_goTypes = []any{
	(ReportAction)(0),             // 0: api.worker.v1.ReportAction
	(*UnregisterRequest)(nil),     // 1: api.worker.v1.UnregisterRequest
	(*UnregisterResponse)(nil),    // 2: api.worker.v1.UnregisterResponse
	(*HeartbeatRequest)(nil),      // 3: api.worker.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 4: api.worker.v1.HeartbeatResponse
	(*PollRequest)(nil),           // 5: api.worker.v1.PollRequest
	(*PollResponse)(nil),          // 6: api.worker.v1.PollResponse
	(*ReportRequest)(nil),         // 7: api.worker.v1.ReportRequest
	(*ReportResponse)(nil),        // 8: api.worker.v1.ReportResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*v1.Task)(nil),               // 10: api.schema.v1.Task
	(*v1.Worker)(nil),             // 11: api.schema.v1.Worker
}
var file_api_worker_v1_rpc_proto_depIdxs = []int32{
	9,  // 0: api.worker.v1.HeartbeatResponse.heartbeat_time:type_name -> google.protobuf.Timestamp
	10, // 1: api.worker.v1.PollResponse.task:type_name -> api.schema.v1.Task
	0,  // 2: api.worker.v1.ReportRequest.action:type_name -> api.worker.v1.ReportAction
	11, // 3: api.worker.v1.WorkerService.Register:input_type -> api.schema.v1.Worker
	1,  // 4: api.worker.v1.WorkerService.Unregister:input_type -> api.worker.v1.UnregisterRequest
	3,  // 5: api.worker.v1.WorkerService.Heartbeat:input_type -> api.worker.v1.HeartbeatRequest
	5,  // 6: api.worker.v1.WorkerService.Poll:input_type -> api.worker.v1.PollRequest
	7,  // 7: api.worker.v1.WorkerService.Report:input_type -> api.worker.v1.ReportRequest
	11, // 8: api.worker.v1.WorkerService.Register:output_type -> api.schema.v1.Worker
	2,  // 9: api.worker.v1.WorkerService.Unregister:output_type -> api.worker.v1.UnregisterResponse
	4,  // 10: api.worker.v1.WorkerService.Heartbeat:output_type -> api.worker.v1.HeartbeatResponse
	6,  // 11: api.worker.v1.WorkerService.Poll:output_type -> api.worker.v1.PollResponse
	8,  // 12: api.worker.v1.WorkerService.Report:output_type -> api.worker.v1.ReportResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_worker_v1_rpc_proto_init() }
func file_api_worker_v1_rpc_proto_init() {
	if File_api_worker_v1_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_worker_v1_rpc_proto_rawDesc), len(file_api_worker_v1_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_worker_v1_rpc_proto_goTypes,
		DependencyIndexes: file_api_worker_v1_rpc_proto_depIdxs,
		EnumInfos:         file_api_worker_v1_rpc_proto_enumTypes,
		MessageInfos:      file_api_worker_v1_rpc_proto_msgTypes,
	}.Build()
	File_api_worker_v1_rpc_proto = out.File
	file_api_worker_v1_rpc_proto_goTypes = nil
	file_api_worker_v1_rpc_proto_depIdxs = nil
}
